Item.create(
  [
    {
      name: '香水',
      description: 'テストテストテスト',
      category_id: '375',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シャネル',
      delivery_cost: 0,
      prefecture_id: '13',
      delivery_date: 0,
      delivery_way: 1,
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '香水',
      description: 'テストテストテスト',
      category_id: '376',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シャネル',
      delivery_cost: 0,
      prefecture_id: '40',
      delivery_date: 0,
      delivery_way: 1,
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'カバン',
      description: 'テストテストテスト',
      category_id: '377',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シャネル',
      delivery_cost: 0,
      prefecture_id: '12',
      delivery_date: 0,
      delivery_way: 1,
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ピアス',
      description: 'テストテストテスト',
      category_id: '378',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シャネル',
      delivery_cost: 0,
      prefecture_id: '23',
      delivery_date: 0,
      delivery_way: 1,
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'サングラス',
      description: 'テストテストテスト',
      category_id: '379',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シャネル',
      delivery_cost: 0,
      prefecture_id: '28',
      delivery_date: 0,
      delivery_way: 1,
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'バッグ',
      description: 'テストテストテスト',
      category_id: '380',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シャネル',
      delivery_cost: 0,
      prefecture_id: '26',
      delivery_date: 0,
      delivery_way: 1,
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'アクセサリー',
      description: 'テストテストテスト',
      category_id: '381',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シャネル',
      delivery_cost: 0,
      prefecture_id: '22',
      delivery_date: 0,
      delivery_way: 1,
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '紙袋',
      description: 'テストテストテスト',
      category_id: '382',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シャネル',
      delivery_cost: 0,
      prefecture_id: '1',
      delivery_date: 0,
      delivery_way: 1,
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'アクセサリー',
      description: 'テストテストテスト',
      category_id: '383',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シャネル',
      delivery_cost: 0,
      prefecture_id: '27',
      delivery_date: 0,
      delivery_way: 1,
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '紙袋',
      description: 'テストテストテスト',
      category_id: '384',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シャネル',
      delivery_cost: 0,
      prefecture_id: '21',
      delivery_date: 0,
      delivery_way: 1,
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'iphoneカバー',
      description: 'テストテストテスト',
      category_id: '408',
      status: 0,
      size: 'FREE SIZE',
      brand: 'sony',
      delivery_cost: 0,
      prefecture_id: '13',
      delivery_date: 0,
      delivery_way: 1,
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'iphoneケース',
      description: 'テストテストテスト',
      category_id: '409',
      status: 0,
      size: 'FREE SIZE',
      brand: 'sony',
      delivery_cost: 0,
      prefecture_id: '40',
      delivery_date: 0,
      delivery_way: 1,
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '加湿器',
      description: 'テストテストテスト',
      category_id: '410',
      status: 0,
      size: 'FREE SIZE',
      brand: 'sony',
      delivery_cost: 0,
      prefecture_id: '12',
      delivery_date: 0,
      delivery_way: 1,
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'マウス',
      description: 'テストテストテスト',
      category_id: '411',
      status: 0,
      size: 'FREE SIZE',
      brand: 'sony',
      delivery_cost: 0,
      prefecture_id: '23',
      delivery_date: 0,
      delivery_way: 1,
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'iphoneカバー',
      description: 'テストテストテスト',
      category_id: '412',
      status: 0,
      size: 'FREE SIZE',
      brand: 'sony',
      delivery_cost: 0,
      prefecture_id: '28',
      delivery_date: 0,
      delivery_way: 1,
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '録音機',
      description: 'テストテストテスト',
      category_id: '413',
      status: 0,
      size: 'FREE SIZE',
      brand: 'sony',
      delivery_cost: 0,
      prefecture_id: '26',
      delivery_date: 0,
      delivery_way: 1,
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'iphone',
      description: 'テストテストテスト',
      category_id: '414',
      status: 0,
      size: 'FREE SIZE',
      brand: 'sony',
      delivery_cost: 0,
      prefecture_id: '22',
      delivery_date: 0,
      delivery_way: 1,
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'テレビ',
      description: 'テストテストテスト',
      category_id: '415',
      status: 0,
      size: 'FREE SIZE',
      brand: 'sony',
      delivery_cost: 0,
      prefecture_id: '1',
      delivery_date: 0,
      delivery_way: 1,
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ライト',
      description: 'テストテストテスト',
      category_id: '416',
      status: 0,
      size: 'FREE SIZE',
      brand: 'sony',
      delivery_cost: 0,
      prefecture_id: '27',
      delivery_date: 0,
      delivery_way: 1,
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '箱',
      description: 'テストテストテスト',
      category_id: '417',
      status: 0,
      size: 'FREE SIZE',
      brand: 'sony',
      delivery_cost: 0,
      prefecture_id: '21',
      delivery_date: 0,
      delivery_way: 1,
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'マフラー',
      description: 'テストテストテスト',
      category_id: '83',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ルイヴィトン',
      delivery_cost: 0,
      prefecture_id: '13',
      delivery_date: 0,
      delivery_way: 1,
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ショルダーカバー',
      description: 'テストテストテスト',
      category_id: '83',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ルイヴィトン',
      delivery_cost: 0,
      prefecture_id: '40',
      delivery_date: 0,
      delivery_way: 1,
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ショルダーバッグ',
      description: 'テストテストテスト',
      category_id: '83',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ルイヴィトン',
      delivery_cost: 0,
      prefecture_id: '12',
      delivery_date: 0,
      delivery_way: 1,
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '二つ折り財布',
      description: 'テストテストテスト',
      category_id: '83',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ルイヴィトン',
      delivery_cost: 0,
      prefecture_id: '23',
      delivery_date: 0,
      delivery_way: 1,
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '赤いやつ',
      description: 'テストテストテスト',
      category_id: '83',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ルイヴィトン',
      delivery_cost: 0,
      prefecture_id: '28',
      delivery_date: 0,
      delivery_way: 1,
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ルイヴィトンノベルティ',
      description: 'テストテストテスト',
      category_id: '83',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ルイヴィトン',
      delivery_cost: 0,
      prefecture_id: '26',
      delivery_date: 0,
      delivery_way: 1,
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'コインケース',
      description: 'テストテストテスト',
      category_id: '83',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ルイヴィトン',
      delivery_cost: 0,
      prefecture_id: '22',
      delivery_date: 0,
      delivery_way: 1,
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '札入れ',
      description: 'テストテストテスト',
      category_id: '83',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ルイヴィトン',
      delivery_cost: 0,
      prefecture_id: '1',
      delivery_date: 0,
      delivery_way: 1,
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ショルダーバッグ',
      description: 'テストテストテスト',
      category_id: '83',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ルイヴィトン',
      delivery_cost: 0,
      prefecture_id: '27',
      delivery_date: 0,
      delivery_way: 1,
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '手提げカバン',
      description: 'テストテストテスト',
      category_id: '83',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ルイヴィトン',
      delivery_cost: 0,
      prefecture_id: '21',
      delivery_date: 0,
      delivery_way: 1,
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '帽子',
      description: 'テストテストテスト',
      category_id: '91',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シュプリーム',
      delivery_cost: 0,
      prefecture_id: '13',
      delivery_date: 0,
      delivery_way: 1,
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'Tシャツ',
      description: 'テストテストテスト',
      category_id: '92',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シュプリーム',
      delivery_cost: 0,
      prefecture_id: '40',
      delivery_date: 0,
      delivery_way: 1,
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'Tシャツ',
      description: 'テストテストテスト',
      category_id: '93',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シュプリーム',
      delivery_cost: 0,
      prefecture_id: '12',
      delivery_date: 0,
      delivery_way: 1,
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ロゴ',
      description: 'テストテストテスト',
      category_id: '94',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シュプリーム',
      delivery_cost: 0,
      prefecture_id: '23',
      delivery_date: 0,
      delivery_way: 1,
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'キーホルダー',
      description: 'テストテストテスト',
      category_id: '95',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シュプリーム',
      delivery_cost: 0,
      prefecture_id: '28',
      delivery_date: 0,
      delivery_way: 1,
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'パーカー',
      description: 'テストテストテスト',
      category_id: '96',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シュプリーム',
      delivery_cost: 0,
      prefecture_id: '26',
      delivery_date: 0,
      delivery_way: 1,
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ミニバッグ',
      description: 'テストテストテスト',
      category_id: '97',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シュプリーム',
      delivery_cost: 0,
      prefecture_id: '22',
      delivery_date: 0,
      delivery_way: 1,
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'Tシャツ',
      description: 'テストテストテスト',
      category_id: '98',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シュプリーム',
      delivery_cost: 0,
      prefecture_id: '1',
      delivery_date: 0,
      delivery_way: 1,
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ミニバッグ',
      description: 'テストテストテスト',
      category_id: '99',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シュプリーム',
      delivery_cost: 0,
      prefecture_id: '27',
      delivery_date: 0,
      delivery_way: 1,
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '帽子',
      description: 'テストテストテスト',
      category_id: '100',
      status: 0,
      size: 'FREE SIZE',
      brand: 'シュプリーム',
      delivery_cost: 0,
      prefecture_id: '21',
      delivery_date: 0,
      delivery_way: 1,
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ポロシャツ',
      description: 'テストテストテスト',
      category_id: '98',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ナイキ',
      delivery_cost: 0,
      prefecture_id: '13',
      delivery_date: 0,
      delivery_way: 1,
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '帽子',
      description: 'テストテストテスト',
      category_id: '98',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ナイキ',
      delivery_cost: 0,
      prefecture_id: '40',
      delivery_date: 0,
      delivery_way: 1,
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ロンT',
      description: 'テストテストテスト',
      category_id: '98',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ナイキ',
      delivery_cost: 0,
      prefecture_id: '12',
      delivery_date: 0,
      delivery_way: 1,
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'スニーカー',
      description: 'テストテストテスト',
      category_id: '98',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ナイキ',
      delivery_cost: 0,
      prefecture_id: '23',
      delivery_date: 0,
      delivery_way: 1,
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'スニーカー',
      description: 'テストテストテスト',
      category_id: '98',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ナイキ',
      delivery_cost: 0,
      prefecture_id: '28',
      delivery_date: 0,
      delivery_way: 1,
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ゴルフ',
      description: 'テストテストテスト',
      category_id: '98',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ナイキ',
      delivery_cost: 0,
      prefecture_id: '26',
      delivery_date: 0,
      delivery_way: 1,
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'スニーカー',
      description: 'テストテストテスト',
      category_id: '98',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ナイキ',
      delivery_cost: 0,
      prefecture_id: '22',
      delivery_date: 0,
      delivery_way: 1,
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ゴルフグローブ',
      description: 'テストテストテスト',
      category_id: '98',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ナイキ',
      delivery_cost: 0,
      prefecture_id: '1',
      delivery_date: 0,
      delivery_way: 1,
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'トレーニングパンツ',
      description: 'テストテストテスト',
      category_id: '98',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ナイキ',
      delivery_cost: 0,
      prefecture_id: '27',
      delivery_date: 0,
      delivery_way: 1,
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'スニーカー',
      description: 'テストテストテスト',
      category_id: '98',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ナイキ',
      delivery_cost: 0,
      prefecture_id: '21',
      delivery_date: 0,
      delivery_way: 1,
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      description: 'テストテストテスト',
      category_id: '306',
      status: 0,
      size: 'FREE SIZE',
      brand: '遊戯王',
      delivery_cost: 0,
      prefecture_id: '13',
      delivery_date: 0,
      delivery_way: 1,
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      description: 'テストテストテスト',
      category_id: '307',
      status: 0,
      size: 'FREE SIZE',
      brand: '遊戯王',
      delivery_cost: 0,
      prefecture_id: '40',
      delivery_date: 0,
      delivery_way: 1,
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      description: 'テストテストテスト',
      category_id: '308',
      status: 0,
      size: 'FREE SIZE',
      brand: '遊戯王',
      delivery_cost: 0,
      prefecture_id: '12',
      delivery_date: 0,
      delivery_way: 1,
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      description: 'テストテストテスト',
      category_id: '309',
      status: 0,
      size: 'FREE SIZE',
      brand: '遊戯王',
      delivery_cost: 0,
      prefecture_id: '23',
      delivery_date: 0,
      delivery_way: 1,
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      description: 'テストテストテスト',
      category_id: '310',
      status: 0,
      size: 'FREE SIZE',
      brand: '遊戯王',
      delivery_cost: 0,
      prefecture_id: '28',
      delivery_date: 0,
      delivery_way: 1,
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      description: 'テストテストテスト',
      category_id: '311',
      status: 0,
      size: 'FREE SIZE',
      brand: '遊戯王',
      delivery_cost: 0,
      prefecture_id: '26',
      delivery_date: 0,
      delivery_way: 1,
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      description: 'テストテストテスト',
      category_id: '312',
      status: 0,
      size: 'FREE SIZE',
      brand: '遊戯王',
      delivery_cost: 0,
      prefecture_id: '22',
      delivery_date: 0,
      delivery_way: 1,
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      description: 'テストテストテスト',
      category_id: '313',
      status: 0,
      size: 'FREE SIZE',
      brand: '遊戯王',
      delivery_cost: 0,
      prefecture_id: '1',
      delivery_date: 0,
      delivery_way: 1,
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      description: 'テストテストテスト',
      category_id: '314',
      status: 0,
      size: 'FREE SIZE',
      brand: '遊戯王',
      delivery_cost: 0,
      prefecture_id: '27',
      delivery_date: 0,
      delivery_way: 1,
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      description: 'テストテストテスト',
      category_id: '315',
      status: 0,
      size: 'FREE SIZE',
      brand: '遊戯王',
      delivery_cost: 0,
      prefecture_id: '21',
      delivery_date: 0,
      delivery_way: 1,
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '財布',
      description: 'テストテストテスト',
      category_id: '20',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ユニクロ',
      delivery_cost: 0,
      prefecture_id: '13',
      delivery_date: 0,
      delivery_way: 1,
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'パンツ',
      description: 'テストテストテスト',
      category_id: '21',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ユニクロ',
      delivery_cost: 0,
      prefecture_id: '40',
      delivery_date: 0,
      delivery_way: 1,
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ワンピース',
      description: 'テストテストテスト',
      category_id: '22',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ユニクロ',
      delivery_cost: 0,
      prefecture_id: '12',
      delivery_date: 0,
      delivery_way: 1,
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ワンピース',
      description: 'テストテストテスト',
      category_id: '23',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ユニクロ',
      delivery_cost: 0,
      prefecture_id: '23',
      delivery_date: 0,
      delivery_way: 1,
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'eeeee',
      description: 'テストテストテスト',
      category_id: '24',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ユニクロ',
      delivery_cost: 0,
      prefecture_id: '28',
      delivery_date: 0,
      delivery_way: 1,
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ネックレス',
      description: 'テストテストテスト',
      category_id: '25',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ユニクロ',
      delivery_cost: 0,
      prefecture_id: '26',
      delivery_date: 0,
      delivery_way: 1,
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'シャツ',
      description: 'テストテストテスト',
      category_id: '26',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ユニクロ',
      delivery_cost: 0,
      prefecture_id: '22',
      delivery_date: 0,
      delivery_way: 1,
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'バッグ',
      description: 'テストテストテスト',
      category_id: '27',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ユニクロ',
      delivery_cost: 0,
      prefecture_id: '1',
      delivery_date: 0,
      delivery_way: 1,
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'スカート',
      description: 'テストテストテスト',
      category_id: '28',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ユニクロ',
      delivery_cost: 0,
      prefecture_id: '27',
      delivery_date: 0,
      delivery_way: 1,
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ハンカチ',
      description: 'テストテストテスト',
      category_id: '29',
      status: 0,
      size: 'FREE SIZE',
      brand: 'ユニクロ',
      delivery_cost: 0,
      prefecture_id: '21',
      delivery_date: 0,
      delivery_way: 1,
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    }
  ]
)