Item.create(
  [
    {
      name: 'マフラー',
      image: 'https://static.mercdn.net/thumb/photos/m84941702622_1.jpg?1567685319',
      description: 'テストテストテスト',
      category_id: '83',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Louisvuitton',
      postage: '送料込み(出品者負担)',
      region: '東京都',
      shipping_date: '1~2日で発送',
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ショルダーカバー',
      image: 'https://static.mercdn.net/thumb/photos/m71477392886_1.jpg?1567519175',
      description: 'テストテストテスト',
      category_id: '83',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Louisvuitton',
      postage: '送料込み(出品者負担)',
      region: '福岡県',
      shipping_date: '1~2日で発送',
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ショルダーバッグ',
      image: 'https://static.mercdn.net/thumb/photos/m65524430191_1.jpg?1567746439',
      description: 'テストテストテスト',
      category_id: '83',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Louisvuitton',
      postage: '送料込み(出品者負担)',
      region: '大阪府',
      shipping_date: '1~2日で発送',
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '二つ折り財布',
      image: 'https://static.mercdn.net/thumb/photos/m63102461817_1.jpg?1567746422',
      description: 'テストテストテスト',
      category_id: '83',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Louisvuitton',
      postage: '送料込み(出品者負担)',
      region: '広島県',
      shipping_date: '1~2日で発送',
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '赤いやつ',
      image: 'https://static.mercdn.net/thumb/photos/m95117137859_1.jpg?1560655907',
      description: 'テストテストテスト',
      category_id: '83',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Louisvuitton',
      postage: '送料込み(出品者負担)',
      region: '神奈川県',
      shipping_date: '1~2日で発送',
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ルイヴィトンノベルティ',
      image: 'https://static.mercdn.net/thumb/photos/m42828175118_1.jpg?1567356572',
      description: 'テストテストテスト',
      category_id: '83',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Louisvuitton',
      postage: '送料込み(出品者負担)',
      region: '愛知県',
      shipping_date: '1~2日で発送',
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'コインケース',
      image: 'https://static.mercdn.net/thumb/photos/m13714081942_1.jpg?1567746369',
      description: 'テストテストテスト',
      category_id: '83',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Louisvuitton',
      postage: '送料込み(出品者負担)',
      region: '兵庫県',
      shipping_date: '1~2日で発送',
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '札入れ',
      image: 'https://static.mercdn.net/thumb/photos/m45439631004_1.jpg?1566974849',
      description: 'テストテストテスト',
      category_id: '83',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Louisvuitton',
      postage: '送料込み(出品者負担)',
      region: '北海道',
      shipping_date: '1~2日で発送',
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ショルダーバッグ',
      image: 'https://static.mercdn.net/thumb/photos/m14905908510_1.jpg?1567746316',
      description: 'テストテストテスト',
      category_id: '83',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Louisvuitton',
      postage: '送料込み(出品者負担)',
      region: '京都府',
      shipping_date: '1~2日で発送',
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '手提げカバン',
      image: 'https://static.mercdn.net/thumb/photos/m55913910014_1.jpg?1567687195',
      description: 'テストテストテスト',
      category_id: '83',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Louisvuitton',
      postage: '送料込み(出品者負担)',
      region: '静岡県',
      shipping_date: '1~2日で発送',
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    }
  ]
)