Item.create(
  [
    {
      name: 'kkkkk',
      image: 'https://static.mercdn.net/thumb/photos/m19918423643_1.jpg?1567739239',
      description: 'テストテストテスト',
      category_id: '91',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '東京都',
      shipping_date: '1~2日で発送',
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'lllll',
      image: 'https://static.mercdn.net/thumb/photos/m63123855714_1.jpg?1560863508',
      description: 'テストテストテスト',
      category_id: '92',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '福岡県',
      shipping_date: '1~2日で発送',
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'mmmmm',
      image: 'https://static.mercdn.net/thumb/photos/m71229259100_1.jpg?1565955141',
      description: 'テストテストテスト',
      category_id: '93',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '大阪府',
      shipping_date: '1~2日で発送',
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'nnnnn',
      image: 'https://static.mercdn.net/thumb/photos/m11717875247_1.jpg?1567739116',
      description: 'テストテストテスト',
      category_id: '94',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '広島県',
      shipping_date: '1~2日で発送',
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ooooo',
      image: 'https://static.mercdn.net/thumb/photos/m19738637297_1.jpg?1565509380',
      description: 'テストテストテスト',
      category_id: '95',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '神奈川県',
      shipping_date: '1~2日で発送',
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ppppp',
      image: 'https://static.mercdn.net/thumb/photos/m31314425956_1.jpg?1564578389',
      description: 'テストテストテスト',
      category_id: '96',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '愛知県',
      shipping_date: '1~2日で発送',
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'qqqqq',
      image: 'https://static.mercdn.net/thumb/photos/m72260797691_1.jpg?1567261085',
      description: 'テストテストテスト',
      category_id: '97',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '兵庫県',
      shipping_date: '1~2日で発送',
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'rrrrr',
      image: 'https://static.mercdn.net/thumb/photos/m81163001985_1.jpg?1566723413',
      description: 'テストテストテスト',
      category_id: '98',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '北海道',
      shipping_date: '1~2日で発送',
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'sssss',
      image: 'https://static.mercdn.net/thumb/photos/m89925214351_1.jpg?1567493152',
      description: 'テストテストテスト',
      category_id: '99',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '京都府',
      shipping_date: '1~2日で発送',
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ttttt',
      image: 'https://static.mercdn.net/thumb/photos/m43999242273_1.jpg?1567231402',
      description: 'テストテストテスト',
      category_id: '100',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '静岡県',
      shipping_date: '1~2日で発送',
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    }
  ]
)