Item.create(
  [
    {
      name: '遊戯王カード',
      image: 'https://static.mercdn.net/thumb/photos/m33648024473_1.jpg?1567607602',
      description: 'テストテストテスト',
      category_id: '306',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: '遊戯王',
      postage: '送料込み(出品者負担)',
      region: '東京都',
      shipping_date: '1~2日で発送',
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      image: 'https://static.mercdn.net/thumb/photos/m24730056847_1.jpg?1567742460',
      description: 'テストテストテスト',
      category_id: '307',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: '遊戯王',
      postage: '送料込み(出品者負担)',
      region: '福岡県',
      shipping_date: '1~2日で発送',
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      image: 'https://static.mercdn.net/thumb/photos/m65277777370_1.jpg?1567742530',
      description: 'テストテストテスト',
      category_id: '308',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: '遊戯王',
      postage: '送料込み(出品者負担)',
      region: '大阪府',
      shipping_date: '1~2日で発送',
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      image: 'https://static.mercdn.net/thumb/photos/m84186423493_1.jpg?1567742362',
      description: 'テストテストテスト',
      category_id: '309',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: '遊戯王',
      postage: '送料込み(出品者負担)',
      region: '広島県',
      shipping_date: '1~2日で発送',
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      image: 'https://static.mercdn.net/thumb/photos/m54337201526_1.jpg?1567742385',
      description: 'テストテストテスト',
      category_id: '310',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: '遊戯王',
      postage: '送料込み(出品者負担)',
      region: '神奈川県',
      shipping_date: '1~2日で発送',
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      image: 'https://static.mercdn.net/thumb/photos/m59222407664_1.jpg?1567519259',
      description: 'テストテストテスト',
      category_id: '311',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: '遊戯王',
      postage: '送料込み(出品者負担)',
      region: '愛知県',
      shipping_date: '1~2日で発送',
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      image: 'https://static.mercdn.net/thumb/photos/m90493795585_1.jpg?1567692511',
      description: 'テストテストテスト',
      category_id: '312',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: '遊戯王',
      postage: '送料込み(出品者負担)',
      region: '兵庫県',
      shipping_date: '1~2日で発送',
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      image: 'https://static.mercdn.net/thumb/photos/m31008681209_1.jpg?1567742523',
      description: 'テストテストテスト',
      category_id: '313',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: '遊戯王',
      postage: '送料込み(出品者負担)',
      region: '北海道',
      shipping_date: '1~2日で発送',
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      image: 'https://static.mercdn.net/thumb/photos/m85437804275_1.jpg?1567712281',
      description: 'テストテストテスト',
      category_id: '314',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: '遊戯王',
      postage: '送料込み(出品者負担)',
      region: '京都府',
      shipping_date: '1~2日で発送',
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '遊戯王カード',
      image: 'https://static.mercdn.net/thumb/photos/m74754459766_1.jpg?1567519753',
      description: 'テストテストテスト',
      category_id: '315',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: '遊戯王',
      postage: '送料込み(出品者負担)',
      region: '静岡県',
      shipping_date: '1~2日で発送',
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    }
  ]
)