Item.create(
  [
    {
      name: 'aaaaa',
      image: 'https://static.mercdn.net/thumb/photos/m63037452152_1.jpg?1564491506',
      description: 'テストテストテスト',
      category_id: '20',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '東京都',
      shipping_date: '1~2日で発送',
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'bbbbb',
      image: 'https://static.mercdn.net/thumb/photos/m61966918151_1.jpg?1567226472',
      description: 'テストテストテスト',
      category_id: '21',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '福岡県',
      shipping_date: '1~2日で発送',
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ccccc',
      image: 'https://static.mercdn.net/thumb/photos/m15507615267_1.jpg?1547620473',
      description: 'テストテストテスト',
      category_id: '22',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '大阪府',
      shipping_date: '1~2日で発送',
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ddddd',
      image: 'https://static.mercdn.net/thumb/photos/m58770637989_1.jpg?1567167572',
      description: 'テストテストテスト',
      category_id: '23',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '広島県',
      shipping_date: '1~2日で発送',
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'eeeee',
      image: 'https://static.mercdn.net/thumb/photos/m28899632827_1.jpg?1567479360',
      description: 'テストテストテスト',
      category_id: '24',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '神奈川県',
      shipping_date: '1~2日で発送',
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'fffff',
      image: 'https://static.mercdn.net/thumb/photos/m28671686495_1.jpg?1564994048',
      description: 'テストテストテスト',
      category_id: '25',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '愛知県',
      shipping_date: '1~2日で発送',
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ggggg',
      image: 'https://static.mercdn.net/thumb/photos/m92513128788_1.jpg?1567493020',
      description: 'テストテストテスト',
      category_id: '26',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '兵庫県',
      shipping_date: '1~2日で発送',
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'hhhhh',
      image: 'https://static.mercdn.net/thumb/photos/m25553823710_1.jpg?1552724339',
      description: 'テストテストテスト',
      category_id: '27',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '北海道',
      shipping_date: '1~2日で発送',
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'iiiii',
      image: 'https://static.mercdn.net/thumb/photos/m40768274914_1.jpg?1567040161',
      description: 'テストテストテスト',
      category_id: '28',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '京都府',
      shipping_date: '1~2日で発送',
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'jjjjj',
      image: 'https://static.mercdn.net/thumb/photos/m17636295167_1.jpg?1567730331',
      description: 'テストテストテスト',
      category_id: '29',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Supreme',
      postage: '送料込み(出品者負担)',
      region: '静岡県',
      shipping_date: '1~2日で発送',
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    }
  ]
)