Item.create(
  [
    {
      name: '香水',
      image: 'https://static.mercdn.net/thumb/photos/m19860366014_1.jpg?1567742764',
      description: 'テストテストテスト',
      category_id: '375',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Chanel',
      postage: '送料込み(出品者負担)',
      region: '東京都',
      shipping_date: '1~2日で発送',
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '香水',
      image: 'https://static.mercdn.net/thumb/photos/m10943042487_1.jpg?1567742732',
      description: 'テストテストテスト',
      category_id: '376',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Chanel',
      postage: '送料込み(出品者負担)',
      region: '福岡県',
      shipping_date: '1~2日で発送',
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'カバン',
      image: 'https://static.mercdn.net/thumb/photos/m55407493672_1.jpg?1564473268',
      description: 'テストテストテスト',
      category_id: '377',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Chanel',
      postage: '送料込み(出品者負担)',
      region: '大阪府',
      shipping_date: '1~2日で発送',
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ピアス',
      image: 'https://static.mercdn.net/thumb/photos/m18858904589_1.jpg?1564462267',
      description: 'テストテストテスト',
      category_id: '378',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Chanel',
      postage: '送料込み(出品者負担)',
      region: '広島県',
      shipping_date: '1~2日で発送',
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'サングラス',
      image: 'https://static.mercdn.net/thumb/photos/m82847249683_1.jpg?1555728242',
      description: 'テストテストテスト',
      category_id: '379',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Chanel',
      postage: '送料込み(出品者負担)',
      region: '神奈川県',
      shipping_date: '1~2日で発送',
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'バッグ',
      image: 'https://static.mercdn.net/thumb/photos/m82700325530_1.jpg?1563458119',
      description: 'テストテストテスト',
      category_id: '380',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Chanel',
      postage: '送料込み(出品者負担)',
      region: '愛知県',
      shipping_date: '1~2日で発送',
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'アクセサリー',
      image: 'https://static.mercdn.net/thumb/photos/m88743941876_1.jpg?1560238101',
      description: 'テストテストテスト',
      category_id: '381',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Chanel',
      postage: '送料込み(出品者負担)',
      region: '兵庫県',
      shipping_date: '1~2日で発送',
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '紙袋',
      image: 'https://static.mercdn.net/thumb/photos/m27559677202_1.jpg?1562500188',
      description: 'テストテストテスト',
      category_id: '382',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Chanel',
      postage: '送料込み(出品者負担)',
      region: '北海道',
      shipping_date: '1~2日で発送',
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'アクセサリー',
      image: 'https://static.mercdn.net/thumb/photos/m46334723137_1.jpg?1565673785',
      description: 'テストテストテスト',
      category_id: '383',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Chanel',
      postage: '送料込み(出品者負担)',
      region: '京都府',
      shipping_date: '1~2日で発送',
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '紙袋',
      image: 'https://static.mercdn.net/thumb/photos/m13830112259_1.jpg?1561347224',
      description: 'テストテストテスト',
      category_id: '384',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Chanel',
      postage: '送料込み(出品者負担)',
      region: '静岡県',
      shipping_date: '1~2日で発送',
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    }
  ]
)