Item.create(
  [
    {
      name: 'iphoneカバー',
      image: 'https://static.mercdn.net/thumb/photos/m78840733107_1.jpg?1567740685',
      description: 'テストテストテスト',
      category_id: '408',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'sony',
      postage: '送料込み(出品者負担)',
      region: '東京都',
      shipping_date: '1~2日で発送',
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'iphoneケース',
      image: 'https://static.mercdn.net/thumb/photos/m35033516877_1.jpg?1567740684',
      description: 'テストテストテスト',
      category_id: '409',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'sony',
      postage: '送料込み(出品者負担)',
      region: '福岡県',
      shipping_date: '1~2日で発送',
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '加湿器',
      image: 'https://static.mercdn.net/thumb/photos/m39449531257_1.jpg?1566973244',
      description: 'テストテストテスト',
      category_id: '410',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'sony',
      postage: '送料込み(出品者負担)',
      region: '大阪府',
      shipping_date: '1~2日で発送',
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'マウス',
      image: 'https://static.mercdn.net/thumb/photos/m81062262660_1.jpg?1563693228',
      description: 'テストテストテスト',
      category_id: '411',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'sony',
      postage: '送料込み(出品者負担)',
      region: '広島県',
      shipping_date: '1~2日で発送',
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'iphoneカバー',
      image: 'https://static.mercdn.net/thumb/photos/m56618560896_1.jpg?1566809691',
      description: 'テストテストテスト',
      category_id: '412',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'sony',
      postage: '送料込み(出品者負担)',
      region: '神奈川県',
      shipping_date: '1~2日で発送',
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '録音機',
      image: 'https://static.mercdn.net/thumb/photos/m48481715106_1.jpg?1564152891',
      description: 'テストテストテスト',
      category_id: '413',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'sony',
      postage: '送料込み(出品者負担)',
      region: '愛知県',
      shipping_date: '1~2日で発送',
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'iphone',
      image: 'https://static.mercdn.net/thumb/photos/m30252054609_1.jpg?1563808428',
      description: 'テストテストテスト',
      category_id: '414',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'sony',
      postage: '送料込み(出品者負担)',
      region: '兵庫県',
      shipping_date: '1~2日で発送',
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'テレビ',
      image: 'https://static.mercdn.net/thumb/photos/m18903820178_1.jpg?1567404126',
      description: 'テストテストテスト',
      category_id: '415',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'sony',
      postage: '送料込み(出品者負担)',
      region: '北海道',
      shipping_date: '1~2日で発送',
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ライト',
      image: 'https://static.mercdn.net/thumb/photos/m21572439951_1.jpg?1567298502',
      description: 'テストテストテスト',
      category_id: '416',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'sony',
      postage: '送料込み(出品者負担)',
      region: '京都府',
      shipping_date: '1~2日で発送',
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '箱',
      image: 'https://static.mercdn.net/thumb/photos/m45712514152_1.jpg?1566699533',
      description: 'テストテストテスト',
      category_id: '417',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'sony',
      postage: '送料込み(出品者負担)',
      region: '静岡県',
      shipping_date: '1~2日で発送',
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    }
  ]
)