Item.create(
  [
    {
      name: 'ポロシャツ',
      image: 'https://static.mercdn.net/thumb/photos/m44620715627_1.jpg?1567489261',
      description: 'テストテストテスト',
      category_id: '98',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Nike',
      postage: '送料込み(出品者負担)',
      region: '東京都',
      shipping_date: '1~2日で発送',
      price: '7800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: '帽子',
      image: 'https://static.mercdn.net/thumb/photos/m42864060416_1.jpg?1567747767',
      description: 'テストテストテスト',
      category_id: '98',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Nike',
      postage: '送料込み(出品者負担)',
      region: '福岡県',
      shipping_date: '1~2日で発送',
      price: '1000',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ロンT',
      image: 'https://static.mercdn.net/thumb/photos/m31285780594_1.jpg?1567598404',
      description: 'テストテストテスト',
      category_id: '98',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Nike',
      postage: '送料込み(出品者負担)',
      region: '大阪府',
      shipping_date: '1~2日で発送',
      price: '2500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'スニーカー',
      image: 'https://static.mercdn.net/thumb/photos/m36940082217_1.jpg?1567322511',
      description: 'テストテストテスト',
      category_id: '98',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Nike',
      postage: '送料込み(出品者負担)',
      region: '広島県',
      shipping_date: '1~2日で発送',
      price: '7700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'スニーカー',
      image: 'https://static.mercdn.net/thumb/photos/m78949758466_1.jpg?1567253477',
      description: 'テストテストテスト',
      category_id: '98',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Nike',
      postage: '送料込み(出品者負担)',
      region: '神奈川県',
      shipping_date: '1~2日で発送',
      price: '6800',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ゴルフ',
      image: 'https://static.mercdn.net/thumb/photos/m85787330636_1.jpg?1566138939',
      description: 'テストテストテスト',
      category_id: '98',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Nike',
      postage: '送料込み(出品者負担)',
      region: '愛知県',
      shipping_date: '1~2日で発送',
      price: '1499',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'スニーカー',
      image: 'https://static.mercdn.net/thumb/photos/m85787330636_1.jpg?1566138939',
      description: 'テストテストテスト',
      category_id: '98',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Nike',
      postage: '送料込み(出品者負担)',
      region: '兵庫県',
      shipping_date: '1~2日で発送',
      price: '3700',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'ゴルフグローブ',
      image: 'https://static.mercdn.net/thumb/photos/m80301038244_1.jpg?1567747965',
      description: 'テストテストテスト',
      category_id: '98',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Nike',
      postage: '送料込み(出品者負担)',
      region: '北海道',
      shipping_date: '1~2日で発送',
      price: '7200',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'トレーニングパンツ',
      image: 'https://static.mercdn.net/thumb/photos/m60905692820_1.jpg?1567747791',
      description: 'テストテストテスト',
      category_id: '98',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Nike',
      postage: '送料込み(出品者負担)',
      region: '京都府',
      shipping_date: '1~2日で発送',
      price: '1500',
      seller_id: '1',
      buyer_id: '',
    },
    {
      name: 'スニーカー',
      image: 'https://static.mercdn.net/thumb/photos/m38984636354_1.jpg?1567747995',
      description: 'テストテストテスト',
      category_id: '98',
      state: '新品、未使用',
      size: 'FREE SIZE',
      brand: 'Nike',
      postage: '送料込み(出品者負担)',
      region: '静岡県',
      shipping_date: '1~2日で発送',
      price: '1080',
      seller_id: '1',
      buyer_id: '',
    }
  ]
)